version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ivcal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: iv_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 25112025
    volumes:
      - pgdata:/var/lib/postgresql/data
    

  backend:
    build: ./backend
    container_name: ivcal-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3002:3001"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: ivcal-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  pgdata:
